version: 2.1

jobs:
  get_all_known_ips:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # overwrites (truncates) the earlier all.knownips.circleci.com.txt
      - run: |
          dig all.knownips.circleci.com A +short | sort > all.knownips.circleci.com.txt
      # git diff returns non-zero exit if there has been a difference
      - run: |
          git diff all.knownips.circleci.com.txt
          
workflows:
  inspect_changes:
    jobs:
      - get_all_known_ips
